### ISSUE TITLE
Add URL location for s3 wallet store

### ISSUE THREAD

**Issue by ghost** [attestantio/dirk#28]
Hello!

Currently, if I use s3 wallet store, I can't control a bucket name/location via dirk. We can [pass](https://github.com/attestantio/dirk/blob/master/core/stores.go#L68) only password to go-eth2-wallet-store-s3 library. This library itself also can't point to a predefined bucket, it [determines](https://github.com/wealdtech/go-eth2-wallet-store-s3/blob/master/store.go#L104-L105) the name of the bucket via AWS_ACCESS_KEY_ID hash.

I see this problem with that approach:
* We need to add permission s3:CreateBucket with Resource:* to dirk SA (or we need to precalculate hash for `AWS_ACCESS_KEY`), or change that after bucket was created
* We can't rotate `AWS_ACCESS_KEY_ID` or use metadata service for getting that because if it will be changed we will create a new empty bucket (so we need manually copy all data from old bucket to a new one)

It would be a good if:
* We already have [location field](https://github.com/attestantio/dirk/blob/master/core/stores.go#L37) in store structure (which is used for file system type store), and we can use that to point out an endpoint for aws-s3-sdk
* If we could use the location field for that, we would be able to control not only bucket name, but also the whole URL ([endpoint](https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config) in AWS SDK), so we would be able to use any s3-compatible services as s3 store.

**Comment by mcdee** [comment]
Can you provide some examples of URLs as location that could be used in place of the region and auto-generation of bucket names, for both S3 and another S3-compatible store, so that I can take a look at this?  Thanks.

**Comment by p2p-sergey-y** [comment]
Yeah, S3 protocol is based upon REST API, so generally all S3-compatible storage has path like `https:/[bucket].[endpoint]/[path]` (AWS and GCS in [interoperability mode](https://cloud.google.com/storage/docs/interoperability)) or `https:/[endpoint]/[bucket]/[path]` (MinIO, [path style](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html)).
AWS S3 SDK constructing URL by itself, where the first style is default one but the second style could be constructed with [WithS3ForcePathStyle](https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config.WithS3ForcePathStyle)

Default endpoints:
1. AWS S3: `https://s3.amazonaws.com`
2. GCS: `https://storage.googleapis.com`
3. MinIO: could be anything in both formats due to reverse proxy

Currently AWS SDK [requires](https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config) `region` anyway, so we need to configure 4 params:
* Endpoint 
* Region
* Bucket name
* Path (folder where to store all data)

While testing aws-sdk I understand, that encode that in one string (for example, like `https://[bucket].s3.[region].amazonaws.com` is not a good thing because a lot of assumptions, mess with classic sdk variant and split/join actions...
So maybe just add all these parameters in dirk config in majordomo style:
```
s3:
  endpoint: <endpoint>
  region: <region>
  bucket: <bucket>

stores:
- name: Remote
  type: s3
  location: s3://<path>
 ```
If config haven't `s3 section` or/and `location` in `stores`, dirk could use current approach, but if it exists - use a new one where dirk will use a existing bucket. Endpoint/region may be an optional with AWS defaults (like right now).

But ideally I want to have a lot of s3 storages, so maybe do like that:
```
s3:
  aws:
    endpoint: <endpoint>
    region: <region>
    bucket: <bucket>
  <any template>:
   ...
stores:
- name: Remote AWS
  type: s3
  location: s3://<path>
  template: aws
- name: Remote
  type: s3
  location: s3://<path>
  template: <template>
```
