### ISSUE TITLE
[Feature Request] Majordomo url for gsm/asm credential file

### ISSUE THREAD

**Issue by SpontaneousOverthrow** [attestantio/dirk#32]
Main idea - to be able to use Majordomo url for gsm/asm credential files instead of simple local file.
Example:
```
s3:
  endpoint: <endpoint>
  region: <region>
  bucket: <bucket>
  credential: <majordomo>
  
```
